+incdir+.
+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
//$UVM_HOME/src/dpi/uvm_dpi.cc
dut/xswitch.svp
verification/dut_top.sv
verification/interface.sv
verification/my_sequences.sv
verification/lab4_pkg.sv
verification/tbench_top.sv